# Generated by Django 5.2 on 2025-04-17 08:54

import userdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=15, validators=[userdata.models.validate_phone]
                    ),
                ),
                ("address", models.TextField()),
                ("consent", models.BooleanField(default=False)),
            ],
        ),
    ]
