# Generated by Django 5.2 on 2025-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_remove_userdata_address_alter_userdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
