# Generated by Django 5.2 on 2025-04-22 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="email",
            field=models.EmailField(
                default="default@example.com",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
