# Generated by Django 5.2 on 2025-05-01 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_userdata_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
